theforeman/foreman_rh_cloud

webpack/ForemanYupana/Components/ReportGenerate/ReportGenerate.js, webpack/ForemanYupana/Components/ReportGenerate/__tests__/ReportGenerate.test.js, webpack/ForemanYupana/Components/ReportGenerate/__tests__/__snapshots__/ReportGenerate.test.js.snap, webpack/ForemanYupana/Components/ReportGenerate/index.js, webpack/ForemanYupana/Components/ReportGenerate/reportGenerate.scss, webpack/ForemanYupana/Components/UploadsDashboard/UploadsDashboard.js, webpack/ForemanYupana/Components/UploadsDashboard/__tests__/__snapshots__/UploadsDashboard.test.js.snap
=> Add report generating tab view

.gitignore, package.json, webpack/ForemanYupana/Components/ReportGenerate/ReportGenerate.js, webpack/ForemanYupana/Components/ReportGenerate/__tests__/__snapshots__/ReportGenerate.test.js.snap, webpack/ForemanYupana/Components/StatusChart/StatusChart.js, webpack/ForemanYupana/Components/StatusChart/__tests__/StatusChart.test.js, webpack/ForemanYupana/Components/StatusChart/__tests__/__snapshots__/StatusChart.test.js.snap, webpack/ForemanYupana/Components/StatusChart/index.js, webpack/ForemanYupana/Components/StatusChart/statusChart.scss, webpack/ForemanYupana/Components/TabBody/TabBody.js, webpack/ForemanYupana/Components/TabBody/__tests__/TabBody.test.js, webpack/ForemanYupana/Components/TabBody/__tests__/__snapshots__/TabBody.test.js.snap, webpack/ForemanYupana/Components/TabBody/index.js, webpack/ForemanYupana/Components/Terminal/Terminal.js, webpack/ForemanYupana/Components/Terminal/__tests__/__snapshots__/Terminal.test.js.snap, webpack/ForemanYupana/Components/Terminal/terminal.scss, webpack/ForemanYupana/Components/UploadsDashboard/UploadsDashboard.fixtures.js, webpack/ForemanYupana/Components/UploadsDashboard/__tests__/__snapshots__/UploadsDashboard.test.js.snap
=> Add progress status

app/controllers/foreman_yupana/react_controller.rb, app/views/foreman_yupana/layouts/react.html.erb, config/routes.rb, lib/foreman_yupana/engine.rb, webpack/ForemanYupana/ForemanYupana.js, webpack/index.js
=> Add Yupana sub menu to foreman

foreman_yupana.gemspec, lib/foreman_yupana/report/generator.rb, lib/tasks/foreman_yupana_tasks.rake, lib/tasks/generator.rake
First version of generator rake task
=> Initial generator code

package.json, webpack/ForemanYupana/Components/StatusChart/StatusChart.js, webpack/ForemanYupana/Components/StatusChart/__tests__/__snapshots__/StatusChart.test.js.snap, webpack/ForemanYupana/Components/StatusChart/statusChart.scss, webpack/ForemanYupana/Components/TabBody/TabBody.js, webpack/ForemanYupana/Components/TabBody/__tests__/__snapshots__/TabBody.test.js.snap, webpack/ForemanYupana/Components/TabContainer/TabContainer.js, webpack/ForemanYupana/Components/TabContainer/__tests__/__snapshots__/TabContainer.test.js.snap, webpack/ForemanYupana/Components/UploadsDashboard/__tests__/UploadsDashboardIntegration.test.js, webpack/ForemanYupana/Components/UploadsDashboard/__tests__/UploadsDashboardSelectors.test.js
=> Refactor the status Donut Chart

webpack/ForemanYupana/Components/Dashboard/Dashboard.js, webpack/ForemanYupana/Components/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap, webpack/ForemanYupana/Components/NavContainer/NavContainer.js, webpack/ForemanYupana/Components/NavContainer/__tests__/NavContainer.test.js, webpack/ForemanYupana/Components/NavContainer/__tests__/__snapshots__/NavContainer.test.js.snap, webpack/ForemanYupana/Components/NavContainer/index.js
*Before:*
```
<TabContainer id="basic-tabs-pf" defaultActiveKey={1}>
<div className="uploads-dashboard">
<Nav bsClass="nav nav-tabs nav-tabs-pf nav-justified">
<NavItem eventKey={1}>
<Icon name="database" size="2x" />
<p>Generating</p>
</NavItem>
<NavItem eventKey={2}>
<Icon name="cloud-upload" size="2x" />
<p>Uploading</p>
</NavItem>
</Nav>
<TabContent animation>
<TabPane eventKey={1}>
<ReportGenerate {...generating} />
</TabPane>
<TabPane eventKey={2}>
<ReportUpload {...uploading} />
</TabPane>
</TabContent>
</div>
</TabContainer>
```
*After:*
```
<NavContainer
items={[
{
icon: 'database',
name: 'Generating',
component: () => <ReportGenerate {...generating} />,
},
{
icon: 'cloud-upload',
name: 'Uploading',
component: () => <ReportUpload {...uploading} />,
},
]}
/>
```
=> Refactor dashboard - break into smaller components

webpack/ForemanYupana/Components/Dashboard/Dashboard.fixtures.js, webpack/ForemanYupana/Components/Dashboard/Dashboard.js, webpack/ForemanYupana/Components/Dashboard/DashboardActions.js, webpack/ForemanYupana/Components/Dashboard/DashboardReducer.js, webpack/ForemanYupana/Components/Dashboard/DashboardSelectors.js, webpack/ForemanYupana/Components/Dashboard/__tests__/DashboardActions.test.js, webpack/ForemanYupana/Components/Dashboard/__tests__/DashboardReducer.test.js, webpack/ForemanYupana/Components/Dashboard/__tests__/__snapshots__/DashboardActions.test.js.snap, webpack/ForemanYupana/Components/Dashboard/__tests__/__snapshots__/DashboardReducer.test.js.snap, webpack/ForemanYupana/Components/Dashboard/index.js, webpack/ForemanYupana/Components/ReportGenerate/ReportGenerate.js, webpack/ForemanYupana/Components/ReportUpload/ReportUpload.js, webpack/ForemanYupana/Components/ReportUpload/ReportUploadActions.js, webpack/ForemanYupana/Components/ReportUpload/ReportUploadSelectors.js, webpack/ForemanYupana/Components/ReportUpload/index.js, webpack/ForemanYupana/__snapshots__/ForemanYupana.test.js.snap
-  and modified `files` to be fetched through the polling process.
- removed hard coded Dashboard props.
=> Fixed double mounting

webpack/ForemanYupana/Components/TabBody/TabBody.js, webpack/ForemanYupana/Components/TabBody/__tests__/__snapshots__/TabBody.test.js.snap, webpack/ForemanYupana/Components/TabContainer/TabContainer.js, webpack/ForemanYupana/Components/TabContainer/__tests__/__snapshots__/TabContainer.test.js.snap, webpack/ForemanYupana/Components/Terminal/Terminal.js, webpack/ForemanYupana/Components/Terminal/__tests__/__snapshots__/Terminal.test.js.snap
=> Remove StatusChart for now

webpack/ForemanYupana/Components/AccountList/AccountList.js, webpack/ForemanYupana/Components/AccountList/Components/ListItem/ListItem.js, webpack/ForemanYupana/Components/AccountList/Components/ListItem/__tests__/__snapshots__/ListItem.test.js.snap, webpack/ForemanYupana/Components/AccountList/__tests__/__snapshots__/AccountList.test.js.snap, webpack/ForemanYupana/Components/Dashboard/Dashboard.fixtures.js, webpack/ForemanYupana/Components/Dashboard/Dashboard.js, webpack/ForemanYupana/Components/Dashboard/DashboardActions.js, webpack/ForemanYupana/Components/Dashboard/DashboardHelper.js, webpack/ForemanYupana/Components/Dashboard/DashboardReducer.js, webpack/ForemanYupana/Components/Dashboard/DashboardSelectors.js, webpack/ForemanYupana/Components/Dashboard/__tests__/Dashboard.test.js, webpack/ForemanYupana/Components/Dashboard/__tests__/DashboardActions.test.js, webpack/ForemanYupana/Components/Dashboard/__tests__/DashboardIntegration.test.js, webpack/ForemanYupana/Components/Dashboard/__tests__/DashboardReducer.test.js, webpack/ForemanYupana/Components/Dashboard/__tests__/DashboardSelectors.test.js, webpack/ForemanYupana/Components/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap, webpack/ForemanYupana/Components/Dashboard/__tests__/__snapshots__/DashboardActions.test.js.snap, webpack/ForemanYupana/Components/Dashboard/__tests__/__snapshots__/DashboardReducer.test.js.snap, webpack/ForemanYupana/Components/Dashboard/index.js, webpack/ForemanYupana/Components/NavContainer/NavContainer.js, webpack/ForemanYupana/Components/NavContainer/__tests__/__snapshots__/NavContainer.test.js.snap
=> Refactor Redux, distinguish actions by accountID

webpack/ForemanYupana/Components/Dashboard/Dashboard.fixtures.js, webpack/ForemanYupana/Components/Dashboard/DashboardActions.js, webpack/ForemanYupana/Components/Dashboard/__tests__/__snapshots__/DashboardActions.test.js.snap
=> Split the terminal logs by '\n' for better display

webpack/ForemanYupana/Components/Dashboard/Dashboard.js
to fetch the logs before the polling even started.
=> Add initial fetchLogs in Dashboard

webpack/ForemanInventoryUpload/Components/TabHeader/TabHeader.js, webpack/ForemanInventoryUpload/Components/TabHeader/__tests__/__snapshots__/TabHeader.test.js.snap, webpack/ForemanInventoryUpload/Components/TabHeader/tabHeader.scss
=> Remove btn group and split between buttons

webpack/ForemanInventoryUpload/Components/NavContainer/NavContainer.js, webpack/ForemanInventoryUpload/Components/NavContainer/__tests__/__snapshots__/NavContainer.test.js.snap, webpack/ForemanInventoryUpload/Components/NavContainer/navContainer.scss
=> unjustify the tabs width

lib/foreman_inventory_upload.rb
Needed for proper work with SELinux enabled
=> Make /var/lib/foreman/ as default root for prod

webpack/ForemanInventoryUpload/Components/AccountList/Components/ErrorState/ErrorState.js, webpack/ForemanInventoryUpload/Components/AccountList/Components/ErrorState/__tests__/__snapshots__/ErrorState.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/Components/ErrorState/errorState.scss
=> Adjust error state style

.travis.yml, lib/foreman_inventory_upload/async/upload_report_job.rb
Cherrypick from master (750f0ad0174aaa6d58062c4c7cf9e4df4bfde283)
=> Use katello http proxy setting

lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
cherry picks https://github.com/theforeman/foreman_inventory_upload/commit/02b309fddcc61fef5d7db0739c036f5226c6e4fb
=> cp foreman_1_20 - move sat id and org id facts to tags

.travis.yml, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
cherry pick 02b309fddcc61fef5d7db0739c036f5226c6e4fb
=> cp foreman_1_24 - move sat id and org id facts to tags

lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
CP 775a4d57e68d47265be0578e74cd634101fcc4cb
=> Fix skipped host json

lib/foreman_inventory_upload/generators/fact_helpers.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
=> convert memsize from kb to bytes

lib/foreman_inventory_upload/generators/fact_helpers.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
(cherry picked from commit 1d90c1981c862ada8bda7ab08aefa33c39ded544)
=> cherry pick 1_24 - convert memsize from kb to bytes

lib/foreman_inventory_upload/generators/fact_helpers.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
(cherry picked from commit 1d90c1981c862ada8bda7ab08aefa33c39ded544)
=> cherry pick 1_20 - convert memsize from kb to bytes

lib/foreman_rh_cloud/version.rb
accidentally on the last cherry-pick the version got overwritten.
=> revert to the right version

webpack/ForemanInventoryUpload/Components/FullScreenModal/fullScreenModal.scss
(cherry picked from commit 201163afb4e4b8c36983b6c7b13e3bc325c349dd)
=> cherry pick to 1.24 - fix fullscreen modal css (#128)

webpack/ForemanInventoryUpload/Components/Dashboard/Dashboard.js, webpack/ForemanInventoryUpload/Components/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap, webpack/ForemanInventoryUpload/Components/ReportUpload/ReportUpload.js, webpack/ForemanInventoryUpload/Components/ReportUpload/__tests__/__snapshots__/ReportUpload.test.js.snap, webpack/ForemanInventoryUpload/Components/TabHeader/TabHeader.js, webpack/ForemanInventoryUpload/Components/TabHeader/__tests__/__snapshots__/TabHeader.test.js.snap
(cherry picked from commit 2a833ba3e0d183851edc49fcc9bfbf5e432103e5)
=> cherry pick to 1.24 - remove 'Restart' button from 'Uploading' tab (#127)

webpack/ForemanInventoryUpload/Components/FullScreenModal/fullScreenModal.scss
(cherry picked from commit 201163afb4e4b8c36983b6c7b13e3bc325c349dd)
=> cherry pick to 1.20 - fix fullscreen modal css (#128)

webpack/ForemanInventoryUpload/Components/Dashboard/Dashboard.js, webpack/ForemanInventoryUpload/Components/Dashboard/__tests__/__snapshots__/Dashboard.test.js.snap, webpack/ForemanInventoryUpload/Components/ReportUpload/ReportUpload.js, webpack/ForemanInventoryUpload/Components/ReportUpload/__tests__/__snapshots__/ReportUpload.test.js.snap, webpack/ForemanInventoryUpload/Components/TabHeader/TabHeader.js, webpack/ForemanInventoryUpload/Components/TabHeader/__tests__/__snapshots__/TabHeader.test.js.snap
(cherry picked from commit 2a833ba3e0d183851edc49fcc9bfbf5e432103e5)
=> cherry pick to 1.20 - remove 'Restart' button from 'Uploading' tab (#127)

app/models/setting/rh_cloud.rb, lib/foreman_inventory_upload/async/generate_all_reports_job.rb, lib/foreman_rh_cloud/engine.rb
(cherry picked from commit a29e1f9da0a021f0b33f6a01fcc4bf575818de78)
=> Cherry-pick to 1.20 - Add allow_auto_inventory_upload setting (#144)

app/models/setting/rh_cloud.rb, lib/foreman_inventory_upload/async/generate_all_reports_job.rb, lib/foreman_rh_cloud/engine.rb
(cherry picked from commit a29e1f9da0a021f0b33f6a01fcc4bf575818de78)
=> Cherry pick to 1.24 - Add allow_auto_inventory_upload setting (#144)

README.md
Adding what I just found out when trying to figure out how to run it without UI
=> When running in satellite, organization_id variable needs to be set

lib/foreman_inventory_upload/generators/fact_helpers.rb, lib/foreman_inventory_upload/generators/queries.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
=> [CP 24] Add cloud identification fields

.travis.yml
(cherry picked from commit 4a1b90ee214e9f706768f4ac6db7b2a790a448b1)
=> [ CP_20 ] Publishing js-test coverage from travis (#203)

app/models/setting/rh_cloud.rb, lib/foreman_inventory_upload/generators/fact_helpers.rb, lib/foreman_inventory_upload/generators/queries.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
=> [CP 24] Add hostname obfuscation from insights-client

app/models/setting/rh_cloud.rb, lib/foreman_inventory_upload/generators/fact_helpers.rb, lib/foreman_inventory_upload/generators/queries.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
=> [CP 20] Add hostname obfuscation from insights-client

app/controllers/foreman_inventory_upload/accounts_controller.rb, lib/foreman_rh_cloud/engine.rb
* Set up permissions for actions in plugin
* Permissions fixes
Co-authored-by: Shimon Shtein <sshtein@redhat.com>
=> Set up permissions for actions in plugin (#212)

.travis.database.yml, .travis.yml, lib/foreman_rh_cloud/engine.rb, script/travis_setup_postgresql_evr.sh
Added the postgresql-evr extension which is needed by Katello.
=> upgrade foreman to develop branch in travis

webpack/ForemanInventoryUpload/Components/AutoUploadSwitcher/autoUploadSwitcher.scss, webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.js, webpack/ForemanInventoryUpload/Components/PageHeader/__tests__/__snapshots__/PageHeader.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/DocsButton.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/__tests__/DocsButton.test.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/__tests__/__snapshots__/DocsButton.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/docsButton.scss, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/index.js, webpack/ForemanInventoryUpload/ForemanInventoryConstants.js, webpack/ForemanInventoryUpload/ForemanInventoryHelpers.js, webpack/ForemanInventoryUpload/__tests__/ForemanInventoryHelpers.test.js, webpack/ForemanInventoryUpload/__tests__/__snapshots__/ForemanInventoryHelpers.test.js.snap
=> Add inventory docs button link

webpack/ForemanInventoryUpload/Components/AutoUploadSwitcher/autoUploadSwitcher.scss, webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.js, webpack/ForemanInventoryUpload/Components/PageHeader/__tests__/__snapshots__/PageHeader.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/DocsButton.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/__tests__/DocsButton.test.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/__tests__/__snapshots__/DocsButton.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/docsButton.scss, webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/index.js, webpack/ForemanInventoryUpload/ForemanInventoryConstants.js, webpack/ForemanInventoryUpload/ForemanInventoryHelpers.js, webpack/ForemanInventoryUpload/__tests__/ForemanInventoryHelpers.test.js, webpack/ForemanInventoryUpload/__tests__/__snapshots__/ForemanInventoryHelpers.test.js.snap
* Add inventory docs button link
* move to docsUrl helper
(cherry picked from commit 6688098abeb4775c0fc36b8be018990017d17f2)
=> [CP_24] Add inventory docs button link (#221)

webpack/ForemanInventoryUpload/Components/PageHeader/components/PageDescription/PageDescription.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/PageDescription/__tests__/__snapshots__/PageDescription.test.js.snap
`.snap` file was updated manually, as I don't have development environment set up. Let me know if that is a problem.
=> Fix typos in PageDescription

app/views/foreman_rh_cloud/react/insights_cloud.html.erb, webpack/InsightsCloudSync/InsightsCloudSync.js, webpack/InsightsCloudSync/InsightsCloudSync.test.js, webpack/InsightsCloudSync/__snapshots__/InsightsCloudSync.test.js.snap
https://github.com/theforeman/foreman_rh_cloud/pull/253 was accidentally closed. Reopening here.
@laviro, it should be ready for another round.
=> Add inventory welcome screen

app/models/setting/rh_cloud.rb
(cherry picked from commit da7b7404e7ec8275c8ff4df93e42a7e203e8e474)
=> [CP_24] set auto_upload initially "off" (#252)

app/models/setting/rh_cloud.rb
(cherry picked from commit da7b7404e7ec8275c8ff4df93e42a7e203e8e474)
Conflicts:
app/models/setting/rh_cloud.rb
=> [CP_22] set auto_upload initially "off" (#252)

webpack/InsightsCloudSync/InsightsCloudSync.js, webpack/InsightsCloudSync/__snapshots__/InsightsCloudSync.test.js.snap
Sorry I didn't notice that before 2.0.9 release...
=> Fix typo in InsightsCloudSync

webpack/InsightsCloudSync/InsightsCloudSync.js, webpack/InsightsCloudSync/__snapshots__/InsightsCloudSync.test.js.snap
Cherry-picking #273 into foreman_1_24 branch.
=> [cherry-pick foreman_1_24] Fix typo in InsightsCloudSync

webpack/InsightsCloudSync/InsightsCloudSync.js, webpack/InsightsCloudSync/__snapshots__/InsightsCloudSync.test.js.snap
Cherry-picking #273 into foreman_1_22 branch.
=> [cherry-pick foreman_1_22] Fix typo in InsightsCloudSync

app/helpers/foreman_inventory_upload_host_helper.rb, db/migrate/20200727111529_add_uuid_column_to_insights_facets.foreman_rh_cloud.rb, lib/insights_cloud.rb, lib/insights_cloud/async/insights_full_sync.rb, test/jobs/insights_full_sync_test.rb
* Add uuid column to insights facet
* Add link to UI
=> [CP 24] Insights hits link (#290)

app/helpers/foreman_inventory_upload_host_helper.rb, db/migrate/20200727111529_add_uuid_column_to_insights_facets.foreman_rh_cloud.rb, lib/insights_cloud.rb, lib/insights_cloud/async/insights_full_sync.rb, test/jobs/insights_full_sync_test.rb
* Add uuid column to insights facet
* Add link to UI
=> [CP 22] Insights hits link (#290)

.github/workflows/js_tests.yml, .travis.yml, script/travis_run_js_tests.sh
(cherry picked from commit 6cb37505454d4b7e34419bcd70bfeb74794a5a1d)
=> [CP_22] Add JS gh action (#303)

.github/workflows/js_tests.yml, .travis.yml, script/travis_run_js_tests.sh
(cherry picked from commit 6cb37505454d4b7e34419bcd70bfeb74794a5a1d)
=> [CP_24] Add JS gh action (#303)

lib/foreman_inventory_upload/async/upload_report_job.rb, test/jobs/upload_report_job_test.rb
This should wait for https://github.com/theforeman/foreman_rh_cloud/pull/312.
Once it's in, I will rebase it with proper message.
=> Cancel upload for organizations without certificate.

lib/foreman_inventory_upload/async/shell_process.rb, lib/foreman_inventory_upload/async/upload_report_job.rb, test/jobs/upload_report_job_test.rb
(cherry picked from commit 8aea2ce7733f9889978e6449db97dd9dda6c8428)
Conflicts:
lib/foreman_inventory_upload/async/shell_process.rb
=> [CP 24] - stop upload if Satellite setting is disconnected (#312)

lib/foreman_inventory_upload/async/shell_process.rb, lib/foreman_inventory_upload/async/upload_report_job.rb, test/jobs/upload_report_job_test.rb
(cherry picked from commit 8aea2ce7733f9889978e6449db97dd9dda6c8428)
Conflicts:	lib/foreman_inventory_upload/async/shell_process.rb
(cherry picked from commit b31f13c15b8058af987ecf1d9478c20923137767)
=> [CP 22] - stop upload if Satellite setting is disconnected (#312)

README.md, lib/foreman_inventory_upload/async/generate_report_job.rb, lib/tasks/insights.rake, lib/tasks/rh_cloud_inventory.rake
Cherry-pick #328 into `foreman_1_24` branch.
=> [CP_24] Add rake tasks for data synchronization from cloud (#328)

README.md, lib/foreman_inventory_upload/async/generate_report_job.rb, lib/tasks/insights.rake, lib/tasks/rh_cloud_inventory.rake
Cherry-pick #328 / #332 into `foreman_1_22` branch.
=> [CP_22] Add rake tasks for data synchronization from cloud (#328)

lib/foreman_inventory_upload/generators/queries.rb, test/unit/slice_generator_test.rb
(cherry picked from commit c7a9ea963209bb2039b19d92983e758876b49bca)
=> [CP_22] - revert only-rhel host filtering (#330)

lib/foreman_inventory_upload/generators/queries.rb, test/unit/slice_generator_test.rb
(cherry picked from commit c7a9ea963209bb2039b19d92983e758876b49bca)
=> [CP_24] - revert only-rhel host filtering (#330)

webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButton.js, webpack/ForemanInventoryUpload/Components/TabHeader/TabHeader.js, webpack/ForemanInventoryUpload/Components/Terminal/Terminal.js, webpack/ForemanInventoryUpload/ForemanInventoryHelpers.js
* Disable inventory sync button while it's loading (#338)
(cherry picked from commit d0e9744684f6a55ffb32fd12b50658bbbdc3a769)
* Disable report generate button while it's loading (#339)
(cherry picked from commit 12be29237d52a1968fc1251b5bf98a06334e4af9)
(cherry picked from commit 907391546625bef01d2fbda25791d73ebfc6c661)
=> [CP_22] - Disable buttons while loading

app/views/foreman_rh_cloud/react/insights_cloud.html.erb, app/views/foreman_rh_cloud/react/inventory_upload.html.erb, app/views/hosts/_insights_tab.html.erb, app/views/layouts/foreman_rh_cloud/application.html.erb, webpack/InsightsCloudSync/InsightsCloudSync.js, webpack/InsightsCloudSync/InsightsCloudSync.test.js, webpack/InsightsHostDetailsTab/InsightsTab.js, webpack/InsightsHostDetailsTab/InsightsTab.scss, webpack/InsightsHostDetailsTab/__tests__/__snapshots__/InsightsTab.test.js.snap
as it will be deprecated in foreman 2.3
=> Refactor mount_react_component to react_component

app/services/foreman_rh_cloud/cloud_auth.rb, lib/foreman_rh_cloud/engine.rb, lib/insights_cloud/async/insights_full_sync.rb, lib/inventory_sync/async/inventory_full_sync.rb
Extract auth logic to a concern,
so it can be easily used in multiple places.
=> Extract cloud authentication

app/services/foreman_rh_cloud/cloud_auth.rb, lib/foreman_rh_cloud/engine.rb, lib/insights_cloud/async/insights_full_sync.rb, lib/inventory_sync/async/inventory_full_sync.rb
Extract auth logic to a concern,
so it can be easily used in multiple places.
=> [CP_22] Extract cloud authentication (#360)

app/services/foreman_rh_cloud/cloud_auth.rb, lib/foreman_rh_cloud/engine.rb, lib/insights_cloud/async/insights_full_sync.rb, lib/inventory_sync/async/inventory_full_sync.rb
Extract auth logic to a concern,
so it can be easily used in multiple places.
=> [CP_24] Extract cloud authentication (#360)

app/models/concerns/rh_cloud_host.rb, lib/foreman_rh_cloud/engine.rb
(cherry picked from commit d8e40e5ff1ed141fa5ab2801a5b4ce7d890705ee)
=> [CP_24] - fix rubocop latest updates errors (#366)

app/models/concerns/rh_cloud_host.rb, lib/foreman_rh_cloud/engine.rb
(cherry picked from commit d8e40e5ff1ed141fa5ab2801a5b4ce7d890705ee)
=> [CP_22] - fix rubocop latest updates errors (#366)

webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButton.js
(cherry picked from commit aa937ebf1ddac67b77b50a8ea27080735e9fca4a)
=> [CP_24] - Set cloudToken prop to not required

webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButton.js
(cherry picked from commit aa937ebf1ddac67b77b50a8ea27080735e9fca4a)
=> [CP_22] - Set cloudToken prop to not required

.eslintrc, webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/IpsObfuscationSwitcher.js, webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/__tests__/__snapshots__/IpsObfuscationSwitcher.test.js.snap
(cherry picked from commit 3bdfb4c24c45cec5609eb10dab926d858aa61ed5)
Conflicts:
.eslintrc
(cherry picked from commit 58b2d5d97c25a268e26d82e711c55ec6873eed29)
=> [CP_22] - Refactor ip obfuscation switcher's text to 'ipv4' (#376)

.eslintrc, webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/IpsObfuscationSwitcher.js, webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/__tests__/__snapshots__/IpsObfuscationSwitcher.test.js.snap
(cherry picked from commit 3bdfb4c24c45cec5609eb10dab926d858aa61ed5)
Conflicts:
.eslintrc
=> [CP_24] - Refactor ip obfuscation switcher's text to 'ipv4' (#376)

lib/foreman_inventory_upload/generators/json_stream.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
(cherry picked from commit 99fcb4220df578f0335e41ce7c5be54000d7d2c5)
=> [CP_22] - omit fields where fact is nil

lib/foreman_inventory_upload/generators/json_stream.rb, lib/foreman_inventory_upload/generators/slice.rb, test/unit/slice_generator_test.rb
(cherry picked from commit 99fcb4220df578f0335e41ce7c5be54000d7d2c5)
=> [CP_24] - omit fields where fact is nil

app/helpers/foreman_inventory_upload_host_helper.rb, app/models/concerns/rh_cloud_host.rb, app/models/insights_hit.rb, app/overrides/hosts_list.rb, db/migrate/20201007115752_add_hits_count_to_insights_facets_table.foreman_rh_cloud.rb, db/migrate/20201007121540_setup_hits_count_cache.foreman_rh_cloud.rb, lib/insights_cloud/async/insights_full_sync.rb, test/unit/insights_facet_test.rb
(cherry picked from commit 18a2d97d44e395f79f3823f6c0880d07ab2076b6)
=> [CP_24] - Add recommendations count sorting in hosts index

app/helpers/foreman_inventory_upload_host_helper.rb, app/models/concerns/rh_cloud_host.rb, app/models/insights_hit.rb, app/overrides/hosts_list.rb, db/migrate/20201007115752_add_hits_count_to_insights_facets_table.foreman_rh_cloud.rb, db/migrate/20201007121540_setup_hits_count_cache.foreman_rh_cloud.rb, lib/insights_cloud/async/insights_full_sync.rb, test/unit/insights_facet_test.rb
(cherry picked from commit 18a2d97d44e395f79f3823f6c0880d07ab2076b6)
=> [CP_22] - Add recommendations count sorting in hosts index

webpack/InsightsHostDetailsTab/InsightsTab.scss
(cherry picked from commit 7947859a7e303dc53996ae76b8939d5368a8749d)
=> [CP_24] - Fix insights tab scrollbar background

webpack/InsightsHostDetailsTab/InsightsTab.scss
(cherry picked from commit 7947859a7e303dc53996ae76b8939d5368a8749d)
=> [CP_22] - Fix insights tab scrollbar background

app/helpers/foreman_inventory_upload_host_helper.rb, lib/foreman_rh_cloud/engine.rb
instead of linking to the cloud recommendations.
=> Link to foreman's host recommendations

.eslintrc, app/controllers/insights_cloud/hits_controller.rb, app/models/insights_hit.rb, config/routes.rb, lib/foreman_rh_cloud/engine.rb, webpack/InsightsCloudSync/Components/InsightsHeader/index.js, webpack/InsightsCloudSync/InsightsCloudSync.js, webpack/InsightsCloudSync/InsightsCloudSync.test.js, webpack/InsightsCloudSync/InsightsCloudSyncActions.js, webpack/InsightsCloudSync/InsightsCloudSyncConstants.js, webpack/InsightsCloudSync/InsightsCloudSyncSelectors.js, webpack/InsightsCloudSync/__snapshots__/InsightsCloudSync.test.js.snap, webpack/InsightsCloudSync/index.js, webpack/__mocks__/foremanReact/Root/Context/ForemanContext.js, webpack/__mocks__/foremanReact/constants.js, webpack/__mocks__/foremanReact/routes/common/PageLayout/PageLayout.js
The plan is to add first the search bar,
and on another PR to create the table that will interact with it
=> Add Insights page layout with search

app/views/foreman_rh_cloud/react/inventory_upload.html.erb, config/routes.rb, lib/foreman_rh_cloud/engine.rb, webpack/ForemanInventoryUpload/Components/InventorySettings/InventorySettings.js, webpack/ForemanInventoryUpload/Components/InventorySettings/InventorySettings.scss, webpack/ForemanInventoryUpload/Components/InventorySettings/__tests__/__snapshots__/InventorySettings.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.js, webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.scss, webpack/ForemanInventoryUpload/Components/PageHeader/__tests__/__snapshots__/PageHeader.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/pageHeader.scss, webpack/ForemanInventoryUpload/ForemanInventoryUpload.js, webpack/ForemanInventoryUpload/__tests__/__snapshots__/ForemanInventoryUpload.test.js.snap, webpack/ForemanRhCloudPages.js, webpack/__mocks__/foremanReact/routes/common/PageLayout/PageLayout.js
Had to make some css changes because after I changed to `PageLayout` it looked less good. Changed the class names to fit the convention :)
=> Move inventory upload to react router

webpack/ForemanInventoryUpload/Components/AutoUploadSwitcher/AutoUploadSwitcher.js, webpack/ForemanInventoryUpload/Components/AutoUploadSwitcher/__tests__/__snapshots__/AutoUploadSwitcher.test.js.snap, webpack/ForemanInventoryUpload/Components/AutoUploadSwitcher/autoUploadSwitcher.scss, webpack/ForemanInventoryUpload/Components/ExcludePackagesSwitcher/ExcludePackagesSwitcher.js, webpack/ForemanInventoryUpload/Components/ExcludePackagesSwitcher/__tests__/__snapshots__/ExcludePackagesSwitcher.test.js.snap, webpack/ForemanInventoryUpload/Components/ExcludePackagesSwitcher/excludePackagesSwitcher.scss, webpack/ForemanInventoryUpload/Components/HostObfuscationSwitcher/HostObfuscationSwitcher.js, webpack/ForemanInventoryUpload/Components/HostObfuscationSwitcher/HostObfuscationSwitcher.scss, webpack/ForemanInventoryUpload/Components/HostObfuscationSwitcher/__tests__/__snapshots__/HostObfuscationSwitcher.test.js.snap, webpack/ForemanInventoryUpload/Components/InventorySettings/InventorySettings.scss, webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/IpsObfuscationSwitcher.js, webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/__tests__/__snapshots__/IpsObfuscationSwitcher.test.js.snap, webpack/ForemanInventoryUpload/ForemanInventoryUpload.js, webpack/ForemanInventoryUpload/__tests__/__snapshots__/ForemanInventoryUpload.test.js.snap, webpack/common/Switcher/HelpLabel.js, webpack/common/Switcher/SwitcherPF4.js, webpack/common/Switcher/SwitcherPF4.scss, webpack/common/Switcher/__tests__/HelpLabel.test.js, webpack/common/Switcher/__tests__/SwitcherPF4.test.js, webpack/common/Switcher/__tests__/__snapshots__/HelpLabel.test.js.snap, webpack/common/Switcher/__tests__/__snapshots__/SwitcherPF4.test.js.snap
Depends on https://github.com/theforeman/foreman_rh_cloud/pull/428
Starting the redesign of  the settings. Next I will need to add "red hat inventory" and "cloud connected"  settings and move the other settings to a modal.
=> Inventory upload setting redesign to pf4

lib/foreman_rh_cloud/engine.rb
(cherry picked from commit 389a37b78dc55b39fbaf3ea829352e151ac76c39)
=> Avoid host base including RhCloudHost module

app/models/setting/rh_cloud.rb
Some settings were missing names. This PR adds them.
=> Add settings names

webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.js, webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.scss, webpack/ForemanInventoryUpload/Components/PageHeader/__tests__/__snapshots__/PageHeader.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/components/SettingsWarning/SettingsWarning.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/SettingsWarning/SettingsWarning.test.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/SettingsWarning/__snapshots__/SettingsWarning.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/components/SettingsWarning/index.js
Will need to use the selector from https://github.com/theforeman/foreman_rh_cloud/pull/458 in order to work
=> Add warning to inventory for settings for cloud connector

webpack/InsightsCloudSync/Components/InsightsTable/InsightsTable.js, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableConstants.js, webpack/InsightsCloudSync/Components/InsightsTable/__tests__/__snapshots__/InsightsTable.test.js.snap
=> Remove mock remediate from insights table

app/controllers/foreman_inventory_upload/uploads_controller.rb, webpack/ForemanInventoryUpload/Components/Dashboard/DashboardActions.js, webpack/ForemanInventoryUpload/Components/Dashboard/__tests__/DashboardActions.test.js
* Fix inventory file download error handling
* open in another tab
(cherry picked from commit c79dd35f8793fc4a4836f74e4071571c57bc1da3)
=> Fix inventory file download error handling (#477)

app/controllers/foreman_inventory_upload/uploads_controller.rb, webpack/ForemanInventoryUpload/Components/Dashboard/DashboardActions.js, webpack/ForemanInventoryUpload/Components/Dashboard/__tests__/DashboardActions.test.js
* Fix inventory file download error handling
* open in another tab
(cherry picked from commit c79dd35f8793fc4a4836f74e4071571c57bc1da3)
=> [CP 1.24] Fix inventory file download error handling (#477) (#488)

app/controllers/foreman_inventory_upload/accounts_controller.rb, test/controllers/accounts_controller_test.rb, webpack/ForemanInventoryUpload/Components/AccountList/AccountList.fixtures.js, webpack/ForemanInventoryUpload/Components/AccountList/AccountList.js, webpack/ForemanInventoryUpload/Components/AccountList/AccountListHelper.js, webpack/ForemanInventoryUpload/Components/AccountList/Components/ListItem/ListItem.fixtures.js, webpack/ForemanInventoryUpload/Components/AccountList/Components/ListItem/ListItem.js, webpack/ForemanInventoryUpload/Components/AccountList/Components/ListItem/__tests__/__snapshots__/ListItem.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/AccountListHelper.test.js, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountList.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListActions.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListReducer.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListSelectors.test.js.snap
(cherry picked from commit a8965e323bd3772923ada0f6c8bdca4da05978dc)
=> handle accounts by label nor id (#495)

app/controllers/foreman_inventory_upload/accounts_controller.rb, test/controllers/accounts_controller_test.rb, webpack/ForemanInventoryUpload/Components/AccountList/AccountList.fixtures.js, webpack/ForemanInventoryUpload/Components/AccountList/AccountList.js, webpack/ForemanInventoryUpload/Components/AccountList/AccountListHelper.js, webpack/ForemanInventoryUpload/Components/AccountList/Components/ListItem/ListItem.fixtures.js, webpack/ForemanInventoryUpload/Components/AccountList/Components/ListItem/ListItem.js, webpack/ForemanInventoryUpload/Components/AccountList/Components/ListItem/__tests__/__snapshots__/ListItem.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/AccountListHelper.test.js, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountList.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListActions.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListReducer.test.js.snap, webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListSelectors.test.js.snap
(cherry picked from commit a8965e323bd3772923ada0f6c8bdca4da05978dc)
(cherry picked from commit e43cebd6560997af79a0a9213b047f1427301c81)
=> handle accounts by label nor id (#495) (#503)

webpack/ForemanInventoryUpload/Components/AccountList/AccountList.fixtures.js, webpack/ForemanInventoryUpload/Components/Dashboard/Dashboard.fixtures.js, webpack/ForemanInventoryUpload/Components/Dashboard/Dashboard.js, webpack/ForemanInventoryUpload/Components/FileDownload/FileDownload.js, webpack/ForemanInventoryUpload/Components/FullScreenModal/FullScreenModal.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/Components/ClearButton/ClearButton.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilter.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/InventoryFilter.test.js, webpack/ForemanInventoryUpload/Components/NavContainer/NavContainer.fixtures.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/__tests__/SyncButton.test.js, webpack/ForemanInventoryUpload/Components/ReportGenerate/ReportGenerate.fixtures.js, webpack/ForemanInventoryUpload/Components/ReportGenerate/ReportGenerate.js, webpack/ForemanInventoryUpload/Components/ReportUpload/ReportUpload.fixtures.js, webpack/ForemanInventoryUpload/Components/ReportUpload/ReportUpload.js, webpack/ForemanInventoryUpload/Components/TabHeader/TabHeader.js, webpack/ForemanInventoryUpload/SubscriptionsPageExtension/InventoryAutoUpload/__tests__/InventoryAutoUpload.test.js, webpack/InsightsCloudSync/Components/InsightsSettings/__tests__/InsightsSettings.test.js, webpack/InsightsCloudSync/Components/InsightsSyncSwitcher/__tests__/InsightsSyncSwitcher.test.js, webpack/InsightsCloudSync/Components/InsightsTable/__tests__/fixtures.js, webpack/InsightsCloudSync/InsightsCloudSync.test.js, webpack/InsightsHostDetailsTab/InsightsTab.js
Working on removing all pf3 starting with `noop`
=> replace pf3 noop with foreman helpers noop

webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilter.fixtures.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilter.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilterReducer.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/InventoryFilter.test.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/InventoryFilterReducer.test.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/__snapshots__/InventoryFilter.test.js.snap, webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/__snapshots__/InventoryFilterReducer.test.js.snap, webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/__snapshots__/integration.test.js.snap, webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/integration.test.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/index.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/inventoryFilter.scss, webpack/__mocks__/foremanReact/components/Layout/LayoutSelectors.js
move organization value updates into `useEffect` and using the layout selector.
Also, using the PF4 input now
=> Fix initial filter term value

db/migrate/20210404000001_change_resolutions.foreman_rh_cloud.rb, lib/insights_cloud.rb, lib/insights_cloud/async/insights_resolutions_sync.rb, lib/insights_cloud/async/insights_rules_sync.rb, test/factories/insights_factories.rb, test/jobs/insights_resolutions_sync_test.rb, test/jobs/insights_rules_sync_test.rb
Contains also https://github.com/theforeman/foreman_rh_cloud/pull/529.
Adds a proper resolutions sync task, so the resolutions could be used in playbook generation.
=> Fix and split resolutions

lib/foreman_rh_cloud.rb, test/unit/rh_cloud_http_proxy_test.rb
Override default behavior of URI class to hide default port for a schema.
=> Add proxy port fix

lib/foreman_rh_cloud/engine.rb
(cherry picked from commit 8bcf6a0d4e29f2e70f0fe42e77af19479fadbad4)
=> BZ #1966932 - Spawn recurring logic from executor init hook (#550)

app/controllers/insights_cloud/api/machine_telemetries_controller.rb, app/models/insights_client_report_status.rb, app/subscribers/foreman_rh_cloud/insights_subscriber.rb, lib/foreman_rh_cloud/engine.rb, test/models/insights_client_report_status_test.rb
* New host status 'Insights reporting'
* Fix issue with getting value of 'host_registration_insights' param
* Fixed issue with host parameter & tests
=> [CP 2.3] New insights status for the host (#425)

webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButtonActions.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/__tests__/__snapshots__/integrations.test.js.snap, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableActions.js, webpack/InsightsCloudSync/Components/InsightsTable/__tests__/__snapshots__/InsightsTableActions.test.js.snap, webpack/InsightsCloudSync/InsightsCloudSync.js, webpack/InsightsCloudSync/InsightsCloudSyncActions.js, webpack/InsightsCloudSync/InsightsCloudSyncConstants.js, webpack/InsightsCloudSync/__tests__/__snapshots__/InsightsCloudSyncActions.test.js.snap, webpack/common/ForemanTasks/ForemanTasksActions.js, webpack/common/ForemanTasks/ForemanTasksHelpers.js, webpack/common/ForemanTasks/index.js
* Task polling for insights sync
* Refactor to ForemnTaskActions
* Properly pass dispatch
* Make tests happy
* Refactor inventory sync
* Make GH test happy
* Make error message more generic
* Code review comments
* Fix double API call
* Make error message more apparent
=> [CP 2.3] Refresh hits after sync (#561)

app/controllers/api/v2/rh_cloud/inventory_controller.rb, app/controllers/concerns/inventory_upload/report_actions.rb, app/controllers/concerns/inventory_upload/task_actions.rb, app/controllers/foreman_inventory_upload/reports_controller.rb, app/controllers/foreman_inventory_upload/tasks_controller.rb, app/controllers/foreman_inventory_upload/uploads_controller.rb, config/routes.rb, test/controllers/inventory_upload/api/inventory_controller_test.rb, test/test_plugin_helper.rb
* Add inventory API actions
* Make rubocop happy
* Review round 1
* Fix inventory_sync action
=> [CP 2.3] Add inventory API actions (#572)

webpack/InsightsCloudSync/Components/RemediationModal/RemediationModal.scss
the remediation modal is not visible properly in reduced browser window.
=> BZ 1967138 - remediation modal vertical nav overlap

app/services/foreman_rh_cloud/cloud_auth.rb, app/services/foreman_rh_cloud/remediations_retriever.rb, lib/insights_cloud/async/insights_full_sync.rb, lib/insights_cloud/async/insights_resolutions_sync.rb, lib/insights_cloud/async/insights_rules_sync.rb, lib/inventory_sync/async/inventory_hosts_sync.rb, lib/inventory_sync/async/inventory_self_host_sync.rb, test/jobs/insights_full_sync_test.rb, test/jobs/insights_resolutions_sync_test.rb, test/jobs/insights_rules_sync_test.rb, test/jobs/inventory_hosts_sync_test.rb, test/jobs/inventory_self_host_sync_test.rb, test/unit/services/foreman_rh_cloud/template_renderer_helper_test.rb
* Skip scheduled actions if token is absent
* Review round 1
=> [CP 2.3] Skip scheduled actions if token is absent (#608)

lib/inventory_sync/async/inventory_full_sync.rb, test/jobs/inventory_full_sync_test.rb
This is a leftover after https://github.com/theforeman/foreman_rh_cloud/pull/608
=> Skip inventory full sync without token

webpack/ForemanInventoryUpload/Components/PageHeader/PageTitle.js, webpack/ForemanInventoryUpload/Components/PageHeader/__tests__/__snapshots__/PageTitle.test.js.snap, webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudPingModal/index.js, webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudPingModal/index.scss, webpack/ForemanInventoryUpload/ForemanInventoryConstants.js
blocked by #610 
this is how the WIP looks at the moment:
https://user-images.githubusercontent.com/26363699/128166493-388984e7-f804-4b1b-bda3-f8155793d318.mp4
=> Add frontend for network status

app/controllers/api/v2/rh_cloud/inventory_controller.rb, lib/foreman_rh_cloud/engine.rb
Generates the following documentation:
=> Add API documentation

webpack/ForemanRhCloudFills.js, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTable.js, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableActions.js, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableConstants.js, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableHelpers.js, webpack/InsightsCloudSync/Components/InsightsTable/__tests__/__snapshots__/InsightsTable.test.js.snap, webpack/InsightsCloudSync/Components/InsightsTable/__tests__/__snapshots__/InsightsTableActions.test.js.snap, webpack/InsightsCloudSync/Components/InsightsTable/table.scss, webpack/InsightsCloudSync/Components/RemediationModal/RemediationModal.scss, webpack/InsightsHostDetailsTab/InsightsTab.scss, webpack/InsightsHostDetailsTab/NewHostDetailsTab.js
https://user-images.githubusercontent.com/26363699/139825314-9e3afd48-3485-4e1d-a927-709db8777461.mp4
=> New Host details insights tab

.eslintrc, app/controllers/insights_cloud/hits_controller.rb, app/models/insights_hit.rb, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTable.js, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableConstants.js, webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableHelpers.js, webpack/InsightsCloudSync/Components/InsightsTable/__tests__/__snapshots__/InsightsTable.test.js.snap, webpack/InsightsCloudSync/Components/ToolbarDropdown.js, webpack/InsightsCloudSync/InsightsCloudSyncHelpers.js, webpack/InsightsHostDetailsTab/NewHostDetailsTab.js, webpack/common/DropdownToggle.js
satellite page | placement | cloud link | link text | in PR
-- | -- | -- | -- | --
/hosts | dropdown per row | https://console.redhat.com/insights/inventory/UUID | "View in Red Hat Inventory" |  
/new/hosts/UUID | main dropdown | https://console.redhat.com/insights/inventory/UUID | "View in Red Hat Inventory" |  
/new/hosts/UUID#/Overview | total-risk chart dropdown | https://console.redhat.com/insights/advisor/systems/UUID | "View in Red Hat Insights"
/new/hosts/UUID#/Insights | main tab dropdown | https://console.redhat.com/insights/advisor/systems/UUID | "View in Red Hat Insights" | V
/new/hosts/UUID#/Insights | dropdown per row | https://console.redhat.com/insights/advisor/recommendations/RECOMMENDATION_UUID | "View in Red Hat Insights" | V
/new/hosts/UUID#/Insights | dropdown per row …
=> Add cloud links

webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilter.js, webpack/ForemanInventoryUpload/Components/InventoryFilter/index.js, webpack/__mocks__/foremanReact/Root/Context/ForemanContext.js, webpack/__mocks__/foremanReact/components/Layout/LayoutSelectors.js
`selectCurrentOrganization` was deprecated in foreman 3.1
=> Switch to `useForemanOrganization`

webpack/ForemanRhCloudFills.js, webpack/InsightsHostDetailsTab/InsightsTab.scss, webpack/InsightsHostDetailsTab/InsightsTabConstants.js, webpack/InsightsHostDetailsTab/InsightsTotalRiskChart.js, webpack/InsightsHostDetailsTab/NewHostDetailsTab.js
https://user-images.githubusercontent.com/26363699/143744638-f48cdffb-6925-489c-b24b-08e0535d51a1.mp4
=> Add total risk chart

.github/images/Dockerfile, .github/images/npm_install_plugins.js, .github/images/run_tests.sh, .github/workflows/build_container.yml
@amirfefer @sharvit @Ron-Lavi 
This introduces and builds a container that we can use for testing plugins.
Any comments? 
You don't have to build your container locally, since it's already published here: https://github.com/ShimShtein/foreman_rh_cloud/pkgs/container/tfm_plugin_test
=> Build container action

.github/images/Dockerfile, .github/images/npm_install_plugins.js, .github/images/run_tests.sh, .github/workflows/build_container.yml
* Add build and publish action
* Switch to pnpm
=> [CP 2.5] Build container action (#677)

.github/images/Dockerfile, .github/images/entrypoint.sh, .github/images/npm_install_plugins.js, .github/images/run_tests.sh, .github/workflows/build_container.yml, .github/workflows/test_container.yml, config/Gemfile.lock.gh_test
* Add build and publish action
* Switch to pnpm
=> Build container action (#677)

app/helpers/foreman_inventory_upload_host_helper.rb
the `host_details_ui` setting should determine the correct host path to redirect.
=> recommendation link to correct host page version

.github/workflows/ruby_tests.yml, app/services/foreman_rh_cloud/cloud_ping_service.rb, test/controllers/inventory_upload/cloud_status_controller_test.rb, test/unit/services/foreman_rh_cloud/cloud_status_service_test.rb, webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudPingModal/index.js
Added reason to certificate auth failure:
=> Add reason to cert failures

app/services/foreman_rh_cloud/cloud_ping_service.rb, test/controllers/inventory_upload/cloud_status_controller_test.rb, test/unit/services/foreman_rh_cloud/cloud_status_service_test.rb, webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudPingModal/index.js
* Add reason to cert failures
* Switch to github container storage
* Fix failing test
=> [CP 2.5] Add reason to cert failures (#698)

webpack/InsightsHostDetailsTab/InsightsTotalRiskChart.js
Change card title from "Total Risks" to "Total risks"
that's all!
=> Fix sentence case for Total risks card

app/controllers/foreman_inventory_upload/uploads_controller.rb, lib/insights_cloud/async/cloud_connector_announce_task.rb, test/jobs/cloud_connector_announce_task_test.rb
@adamruzicka Can you take a look?
=> Move sources announcement after configuration job

app/controllers/api/v2/rh_cloud/cloud_request_controller.rb, test/controllers/insights_cloud/api/cloud_request_controller_test.rb
Alternative to -- https://github.com/ShimShtein/yggdrasil-worker-forwarder/pull/11
=> Allow capitalized JSON keys

lib/foreman_rh_cloud/engine.rb, webpack/ForemanRhCloudFills.js
Taking over from https://github.com/theforeman/foreman_rh_cloud/pull/706
=> Refs #33010 - Fix slot ID and update requires_foreman version

.github/workflows/ruby_tests.yml, app/services/foreman_rh_cloud/cert_auth.rb, app/services/foreman_rh_cloud/cloud_ping_service.rb, app/services/foreman_rh_cloud/cloud_presence.rb, app/services/foreman_rh_cloud/cloud_request_forwarder.rb
This helps supporting keys from all types, not only RSA
=> Use generic openssl read key method

db/migrate/20221102110254_fix_rh_cloud_settings_category_to_dsl.rb
See:
https://github.com/theforeman/foreman/pull/9524
https://github.com/theforeman/foreman/pull/9524#issuecomment-1404661119
=> Migration error 'column settings.category does not exist'

lib/foreman_inventory_upload/generators/fact_helpers.rb, lib/foreman_inventory_upload/generators/metadata.rb, test/unit/metadata_generator_test.rb
@ShimShtein Let me know how this looks?
=> Update report metadata to include system info
