theforeman/foreman_rh_cloud

- webpack/ForemanYupana/Components/ReportGenerate/__tests__/__snapshots__/ReportGenerate.test.js.snap
- webpack/ForemanYupana/Components/ReportUpload/ReportUpload.js
- webpack/ForemanYupana/Components/ReportUpload/__tests__/__snapshots__/ReportUpload.test.js.snap
- webpack/ForemanYupana/Components/TabHeader/TabHeader.js
- webpack/ForemanYupana/Components/TabHeader/__tests__/__snapshots__/TabHeader.test.js.snap
- webpack/ForemanYupana/Components/TabHeader/tabHeader.scss
Now while switching between the inner tabs, the tab container height won't jump because of the additional button in the uploading tab.
> Move download button to the Tab Header

- webpack/ForemanYupana/Components/Dashboard/Dashboard.js
- webpack/ForemanYupana/Components/ReportGenerate/ReportGenerate.fixtures.js
- webpack/ForemanYupana/Components/ReportGenerate/ReportGenerate.js
- webpack/ForemanYupana/Components/ReportGenerate/__tests__/__snapshots__/ReportGenerate.test.js.snap
- webpack/ForemanYupana/Components/ReportUpload/ReportUpload.fixtures.js
- webpack/ForemanYupana/Components/ReportUpload/ReportUpload.js
- webpack/ForemanYupana/Components/ReportUpload/__tests__/__snapshots__/ReportUpload.test.js.snap
- webpack/ForemanYupana/Components/TabBody/TabBody.js
- webpack/ForemanYupana/Components/TabBody/__tests__/__snapshots__/TabBody.test.js.snap
- webpack/ForemanYupana/Components/TabHeader/TabHeader.js
- webpack/ForemanYupana/Components/Terminal/Terminal.fixtures.js
- webpack/ForemanYupana/Components/Terminal/Terminal.js
Instead of showing a black screen, while exitCode is running, show the loading spinner:
removed the loading prop as it wasn't used.
> Show terminal spinner when exit code is 'running'

- lib/foreman_yupana/engine.rb
Change it into something that makes more sense:
I tried to enter "Inventory Uploads" though it was too long..
> Change Yupana menu button icon and text

- webpack/ForemanYupana/Components/Dashboard/Dashboard.js
You can see the logs immediately on switching tabs, instead of waiting 5 seconds
> Fix logs polling lagging when switching between tabs

- webpack/ForemanInventoryUpload/Components/Terminal/Terminal.js
on the packaging PR, koji was complaining it can't find the `lodash/isEqual` module,
changing the import fixed it.
> import isEqual directly from lodash

- app/controllers/foreman_inventory_upload/uploads_controller.rb
- lib/foreman_inventory_upload.rb
when file is moved to `uploads/done/` the download file action raise an error that the file doesn't exists in `uploads/`.
in this PR the `download_file` action will look also if the file was moved to the `done/` folder.
I also added `uploads_file_path`, `done_folder`, `done_file_path` properties 
to `lib/foreman_inventory_upload.rb`
> Fix download file path

- lib/foreman_inventory_upload/generators/queries.rb
- lib/foreman_inventory_upload/generators/slice.rb
- test/unit/slice_generator_test.rb
System profile's "infrastructure_type" field should be reported as "virtual" or "physical"
> BZ 1824183 - add infrastructure_type field to system_profile

- lib/foreman_inventory_upload/async/async_helpers.rb
- lib/foreman_inventory_upload/async/shell_process.rb
Description of problem:
schedule inventory plugin sync failed due to 'organization_id' typecasting.
```bash
2020-04-17T10:01:22 [I|app|] Performed ForemanInventoryUpload::Async::GenerateAllReportsJob (Job ID: 160d2769-88b7-4a3f-96b6-f803d
42c675a) from Dynflow(default) in 6512.74ms
2020-04-17T10:01:22 [I|app|] Performing ForemanInventoryUpload::Async::GenerateReportJob (Job ID: d5b032b1-ccfd-44a2-8444-2c4a5f91
4518) from Dynflow(default) with arguments: "/var/lib/foreman/red_hat_inventory/generated_reports/", 1
2020-04-17T10:01:22 [E|app|] Error performing ForemanInventoryUpload::Async::GenerateReportJob (Job ID: d5b032b1-ccfd-44a2-8444-2c
4a5f914518) from Dynflow(default) in 0.62ms: TypeError (no implicit conversion of Integer into String): …
```
> BZ 1825760 - stringify env hash keys and values

- .travis.yml
Foreman 2.1 moves to rails 6. The setup for rails 6 and latest Katello is not stable yet.
> Freeze the master branch to work with foreman 2.0

- script/travis_run_js_tests.sh
After @ShimShtein comment on the 1.20 CP.
I realized that I didn't change the branch name from `master` to `foreman_1_24`
> [1_24] Fix branch name in travis js tests script

- script/travis_run_js_tests.sh
the JS tests stopped from running with the error:
```bash
git diff --name-only origin/foreman_1_24..HEAD webpack/ .travis.yml .babelrc .eslintrc package.json | wc -l 
fatal: ambiguous argument 'origin/foreman_1_24..HEAD': unknown revision or path not in the working tree.
```
> [master] fix travis js script

- script/travis_run_js_tests.sh
the JS tests stopped from running with the error:
```bash
git diff --name-only origin/foreman_1_24..HEAD webpack/ .travis.yml .babelrc .eslintrc package.json | wc -l 
fatal: ambiguous argument 'origin/foreman_1_24..HEAD': unknown revision or path not in the working tree.
```
> [24] fix travis js script

- webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.js
- webpack/ForemanInventoryUpload/Components/PageHeader/__tests__/__snapshots__/PageHeader.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/DocsButton.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/__tests__/__snapshots__/DocsButton.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/docsButton.scss
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/HistoryButton.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/__tests__/HistoryButton.test.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/__tests__/__snapshots__/HistoryButton.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/index.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/ToolbarButtons.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/__tests__/ToolbarButtons.test.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/__tests__/__snapshots__/ToolbarButtons.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/index.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/toolbarButtons.scss
- webpack/ForemanInventoryUpload/ForemanInventoryConstants.js
- webpack/ForemanInventoryUpload/ForemanInventoryHelpers.js
* Add tasks history button link
* split ToolbarButtons into smaller components
(cherry picked from commit ae82399)
Conflicts:
webpack/ForemanInventoryUpload/ForemanInventoryHelpers.js
Downgrade tests
> [CP 24] - Add tasks history button link

- webpack/ForemanInventoryUpload/Components/PageHeader/PageHeader.js
- webpack/ForemanInventoryUpload/Components/PageHeader/__tests__/__snapshots__/PageHeader.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/DocsButton.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/__tests__/__snapshots__/DocsButton.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/DocsButton/docsButton.scss
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/HistoryButton.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/__tests__/HistoryButton.test.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/__tests__/__snapshots__/HistoryButton.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/HistoryButton/index.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/ToolbarButtons.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/__tests__/ToolbarButtons.test.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/__tests__/__snapshots__/ToolbarButtons.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/index.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/toolbarButtons.scss
- webpack/ForemanInventoryUpload/ForemanInventoryConstants.js
- webpack/ForemanInventoryUpload/ForemanInventoryHelpers.js
* Add action history button link (#239)
* Add tasks history button link
* split ToolbarButtons into smaller components
(cherry picked from commit ae8239937d1fbbfd2a7cc894107bbd950b076edd)
Conflicts:
webpack/ForemanInventoryUpload/ForemanInventoryHelpers.js
* downgrade tests
(cherry picked from commit 8af94de34e90a0068093aac2cb3aa23a80d11618)
> [CP 22] - Add tasks history button link (#243)

- lib/foreman_inventory_upload/async/shell_process.rb
- lib/foreman_inventory_upload/async/upload_report_job.rb
- lib/foreman_inventory_upload/scripts/uploader.sh.erb
Executing the script directly causes SELinux issues because the dynflow workers running in `foreman_rails_t` are not allowed to execute things of type `foreman_lib_t`. By wrapping the execution in a shell we work around this we effectively work around the original issue because `foreman_rails_t` is apparently allowed to execute `bin_t`.
> Fixes #TBFL - Work around SELinux issues when uploading reports

- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/components/Toast.js
subscriprion -> subscription
Rephrased this line of message a little to be more formal. Fact that we are talking about number of hosts is obvious from context - some number will appear right after this message, in the same line.
> Fix typo in hosts sync toast

- .eslintrc
- .github/workflows/js_tests.yml
- package.json
- webpack/ForemanInventoryUpload/Components/StatusChart/StatusChart.js
- webpack/ForemanInventoryUpload/Components/StatusChart/__tests__/__snapshots__/StatusChart.test.js.snap
In the past, it did happen that typo in user-facing string slipped in and made it into released version. I thought it might be useful to prevent this from happening again and include spell-checker in development pipeline.
This PR adds [eslint-plugin-spellcheck](https://github.com/aotaduy/eslint-plugin-spellcheck) module, which does exactly that. I added new entries to eslint configuration and new `npm run` command, as well as included this command in github actions workflow.
New `npm run` is required, because `tfm-lint` ignores existing eslintrc file and provides no way to change this behavior during runtime.
Second commit fixes one spurious spelling mistake found by running `npm run lint:spelling`. ~~Spell checker still complains about "subscriprion" - this is addressed in #326 . That's …
> Run spell-checker over JavaScript files for each PR

- .eslintrc
- package.json
- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/components/Toast.js
- webpack/ForemanInventoryUpload/Components/StatusChart/StatusChart.js
- webpack/ForemanInventoryUpload/Components/StatusChart/__tests__/__snapshots__/StatusChart.test.js.snap
- webpack/stories/decorators/withCardsDecorator.js
* Run spell-checker over JavaScript files for each PR (#327)
* Add eslint spell-checker plugin and npm command to run it
* Fix typo in chart id: "donunt" -> "donut"
(cherry picked from commit e06b521add9fdab069973406826343be9810dd38)
Conflicts:
.eslintrc
package.json
* Fix typo in hosts sync toast
(cherry picked from commit 3839714b5d7ea45ac2735722d52d03335f2d4645)
* Fix eslint spelling error in story styles
* Refactor lint script
Co-authored-by: Mirek Długosz <mzalewsk@redhat.com>
(cherry picked from commit c5992a66ca1082fb3647d19e9208264875c729fb)
> [CP_22] - Add eslint spell-checker (#329)

- lib/tasks/rh_cloud_inventory.rake
- test/unit/slice_generator_test.rb
Hostgroup tag was missing form the report, since the report was not running under a specific user. Now the report will run under administrator permissions.
> Run the generation task as admin

- lib/foreman_inventory_upload/async/upload_report_job.rb
- lib/foreman_rh_cloud.rb
- lib/insights_cloud/async/insights_full_sync.rb
- lib/inventory_sync/async/inventory_full_sync.rb
- test/unit/rh_cloud_http_proxy_test.rb
(cherry picked from commit 1c3675c30c0664653707984ac9860aef56089967)
Conflicts:
lib/foreman_inventory_upload/async/upload_report_job.rb
> [CP_24] - Reuse http_proxy_string in RestClient requests

- lib/foreman_inventory_upload/async/upload_report_job.rb
- lib/foreman_rh_cloud.rb
- lib/insights_cloud/async/insights_full_sync.rb
- lib/inventory_sync/async/inventory_full_sync.rb
- test/unit/rh_cloud_http_proxy_test.rb
(cherry picked from commit 1c3675c30c0664653707984ac9860aef56089967)
Conflicts:
lib/foreman_inventory_upload/async/upload_report_job.rb
> [CP_22] - Reuse http_proxy_string in RestClient requests

- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButton.js
To disable double API calls to fetch host inventory from the cloud.
> Disable inventory sync button while it's loading

- webpack/ForemanInventoryUpload/Components/AccountList/AccountListActions.js
- webpack/ForemanInventoryUpload/Components/AccountList/__tests__/AccountListActions.test.js
- webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListActions.test.js.snap
Adds a toast with error message:
> Add toast with error message for generate report action

- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButton.js
There is this warning in the console:
And also since we can handle when string is empty or null, the prop doesn't have to be required.
> Set cloudToken prop to not required

- .eslintrc
- webpack/ForemanInventoryUpload/Components/AccountList/AccountListActions.js
- webpack/ForemanInventoryUpload/Components/AccountList/__tests__/AccountListActions.test.js
- webpack/ForemanInventoryUpload/Components/AutoUploadSwitcher/AutoUploadSwitcherActions.js
- webpack/ForemanInventoryUpload/Components/AutoUploadSwitcher/__tests__/AutoUploadSwitcherActions.test.js
- webpack/ForemanInventoryUpload/Components/Dashboard/DashboardActions.js
- webpack/ForemanInventoryUpload/Components/Dashboard/__tests__/DashboardActions.test.js
- webpack/ForemanInventoryUpload/Components/ExcludePackagesSwitcher/ExcludePackagesSwitcherActions.js
- webpack/ForemanInventoryUpload/Components/ExcludePackagesSwitcher/__tests__/ExcludePackagesSwitcherActions.test.js
- webpack/ForemanInventoryUpload/Components/ExcludePackagesSwitcher/__tests__/integration.test.js
- webpack/ForemanInventoryUpload/Components/HostObfuscationSwitcher/HostObfuscationSwitcherActions.js
- webpack/ForemanInventoryUpload/Components/HostObfuscationSwitcher/__tests__/HostObfuscationSwitcherActions.test.js
- webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/IpsObfuscationSwitcherActions.js
- webpack/ForemanInventoryUpload/Components/IpsObfuscationSwitcher/__tests__/IpsObfuscationSwitcherActions.test.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButtonActions.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/__tests__/SyncButtonActions.test.js
- webpack/InsightsCloudSync/Components/InsightsSettings/InsightsSettingsActions.js
- webpack/InsightsCloudSync/Components/InsightsSettings/__tests__/InsightsSettingsActions.test.js
- webpack/InsightsCloudSync/InsightsCloudSyncActions.js
- webpack/InsightsHostDetailsTab/InsightsTabActions.js
- webpack/InsightsHostDetailsTab/__tests__/InsightsTabActions.test.js
- webpack/__mocks__/foremanReact/redux/API.js
`'foremanReact/API'` is deprecated since foreman 1.24
> change deprecated api path to the new one

- lib/foreman_rh_cloud/engine.rb
There are some errors related to the fact we want to use the managed host and not the base host.
> Avoid host base including RhCloudHost module

- app/controllers/insights_cloud/hits_controller.rb
- app/controllers/insights_cloud/settings_controller.rb
- app/models/setting/rh_cloud.rb
- config/routes.rb
- package.json
- webpack/InsightsCloudSync/Components/ErrorEmptyState.js
- webpack/InsightsCloudSync/Components/InsightsHeader/InsightsHeader.scss
- webpack/InsightsCloudSync/Components/InsightsHeader/index.js
- webpack/InsightsCloudSync/Components/InsightsSettings/insightsSettings.scss
- webpack/InsightsCloudSync/Components/NoTokenEmptyState.js
- webpack/InsightsCloudSync/Components/__tests__/ErrorEmptyState.test.js
- webpack/InsightsCloudSync/Components/__tests__/InsightsHeader.test.js
- webpack/InsightsCloudSync/Components/__tests__/NoTokenEmptyState.test.js
- webpack/InsightsCloudSync/Components/__tests__/__snapshots__/ErrorEmptyState.test.js.snap
- webpack/InsightsCloudSync/Components/__tests__/__snapshots__/InsightsHeader.test.js.snap
- webpack/InsightsCloudSync/Components/__tests__/__snapshots__/NoTokenEmptyState.test.js.snap
- webpack/InsightsCloudSync/InsightsCloudSync.js
- webpack/InsightsCloudSync/InsightsCloudSync.test.js
- webpack/InsightsCloudSync/InsightsCloudSyncConstants.js
- webpack/InsightsCloudSync/InsightsCloudSyncSelectors.js
- webpack/InsightsCloudSync/__snapshots__/InsightsCloudSync.test.js.snap
- webpack/InsightsCloudSync/index.js
- webpack/__mocks__/foremanReact/redux/API/APISelectors.js
- webpack/__mocks__/foremanReact/redux/API/index.js
- webpack/__mocks__/foremanReact/routes/RouterSelector.js
Depends on: https://github.com/theforeman/foreman_rh_cloud/pull/421
Added the following empty states:
- Loading: when the table pr will be available I'll change the condition to: `status === 'PENDING' && !data.length`
- Error: shows the error that was received
- No token: if the token length is less than 1 then the user is shown instructions on how to add a token:
Also changed the default value for the token setting to be empty
> Add empty states to insights page

- package.json
Matching foreman 2.3 packages.
vendor 4.0 doesn't have pf4, 4.14 has pf4 
* updated prettier to match foreman 
* Removed unused package raf
> update theforeman npm packages to 4.14

- README.md
- lib/tasks/rh_cloud_inventory.rake
Add two more rake tasks, to enable full plugin functionality from command line:
* `rh_cloud_inventory:report:generate_upload` will both generate and upload report
* `rh_cloud_inventory:report:upload` will upload report from directory specified by `target` environment variable; it very much requires to call `rh_cloud_inventory:report:generate` first
This is requested by Insights QE team, who are working on end-to-end FiFi scenarios, and they don't want to involve entire UI interaction machinery only to upload report.
> Add rake tasks for report upload and generate + upload together

- webpack/ForemanInventoryUpload/Components/Terminal/terminal.scss
When a user opens the accordion the page "jumps" and gets bigger because the terminal didn't wrap at the correct place and a horizontal scroll was added.
before:
after:
> Add css overflow to terminal text

- webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilterReducer.js
When translation is on and "any org" is selected the inventory filter should show blank instead of the translated "any org"
> translate any org string in inventory filter reducer

- lib/foreman_inventory_upload.rb
- lib/foreman_inventory_upload/generators/archived_report.rb
the default gzip files become too large, let's change it to xz that should compress the files much more efficiently.
This can go in once https://github.com/quipucords/yupana/pull/336 goes in.
> Change compression algo for reports to xz

- app/controllers/foreman_inventory_upload/accounts_controller.rb
- app/controllers/foreman_inventory_upload/uploads_controller.rb
- app/services/foreman_rh_cloud/cloud_connector.rb
- config/routes.rb
- webpack/ForemanInventoryUpload/Components/AccountList/AccountList.fixtures.js
- webpack/ForemanInventoryUpload/Components/AccountList/AccountListReducer.js
- webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListActions.test.js.snap
- webpack/ForemanInventoryUpload/Components/AccountList/__tests__/__snapshots__/AccountListReducer.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudConnectorButton/CloudConnectorActions.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudConnectorButton/CloudConnectorButton.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudConnectorButton/CloudConnectorSelectors.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudConnectorButton/__tests__/__snapshots__/CloudConnectorButton.test.js.snap
- webpack/ForemanInventoryUpload/Components/PageHeader/components/CloudConnectorButton/index.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/ToolbarButtons/toolbarButtons.scss
Changed the wording for the pending button to match the success toast.
Used the buttons pending state.
User can now reconfigure the cloud connector instead the button being disabled when the cloud connector is configured.
> Cloud connector button shows job pending

- app/controllers/foreman_inventory_upload/uploads_controller.rb
- webpack/ForemanInventoryUpload/Components/Dashboard/DashboardActions.js
- webpack/ForemanInventoryUpload/Components/Dashboard/__tests__/DashboardActions.test.js
Since we moved to react-router pages, there is a problem to throw an error doing a full-page reload.
In this PR we will get the file and the error with a JSON request.
> Fix inventory file download error handling

- app/models/setting/rh_cloud.rb
@ezr-ondrej, does it look like a valid solution?
The behaviour I am looking for is for new users set the default to `true`.
For users that are upgrading from previous versions and were relying on the fact that the default was `false`, I want to set the value to `false` explicitly.
> Set default autoupload value to true

- webpack/InsightsCloudSync/Components/InsightsTable/InsightsTable.js
- webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableActions.js
- webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableSelectors.js
- webpack/InsightsCloudSync/Components/InsightsTable/SelectAllAlert.js
- webpack/InsightsCloudSync/Components/InsightsTable/__tests__/InsightsTableActions.test.js
- webpack/InsightsCloudSync/Components/InsightsTable/__tests__/__snapshots__/InsightsTableActions.test.js.snap
- webpack/InsightsCloudSync/Components/InsightsTable/__tests__/__snapshots__/InsightsTableSelectors.test.js.snap
- webpack/InsightsCloudSync/Components/InsightsTable/__tests__/fixtures.js
- webpack/__mocks__/foremanReact/redux/API/index.js
Insights table will be opened with selectAll= true from the navigation.
un-selecting all/one of the hosts will set selectAll =false in the url.
url params can't be boolean so the selector is ```isSelectAll === true ||  isSelectAll === 'true'; ``` because `!!'false' === true`.
Missing action tests.
> Add select all to url in insights

- lib/foreman_inventory_upload.rb
returning all of the hosts from c.r.c can take a lot of time,
we can filter to the specific hosts with the satellite instance tag
> Add tags to inventory_export_url

- lib/foreman_inventory_upload.rb
returning all of the host from c.r.c can take a lot of time,
we can filter to the specific hosts with the satellite instance tag
(cherry picked from commit 7bff0a8056263d3281d5ea45e623894f0530ba9e)
> Add tags to inventory_export_url (#489)

- app/services/foreman_rh_cloud/branch_info.rb
- lib/foreman_inventory_upload/generators/slice.rb
- lib/foreman_inventory_upload/generators/tags.rb
- test/test_plugin_helper.rb
- test/unit/services/foreman_rh_cloud/branch_info_test.rb
- test/unit/slice_generator_test.rb
- test/unit/tags_generator_test.rb
Now the tags that are reported by rh_cloud are identical to those reported by insights-client (via the `branch_info` method)
> Sync rh_cloud tags with branch_info

- webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilter.fixtures.js
- webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilterReducer.js
- webpack/ForemanInventoryUpload/Components/InventoryFilter/__tests__/InventoryFilterReducer.test.js
in foreman-2.3 org isn't passed in the layout action payload,
instead it got changed into `organization`
> fix layout change org undefined error

- app/services/foreman_rh_cloud/cloud_connector.rb
Given the host that represents Foreman can only exist in one organization,
if a user has set a different taxonomy on the uploads page the
cloud connector will fail with a 404. The code needs to ignore
taxonomies when running cloud connector to ensure that it runs
no matter the context the user is in.
> Do not set taxonomy when enabling cloud connector

- app/services/foreman_rh_cloud/cloud_request_forwarder.rb
- test/controllers/insights_cloud/api/machine_telemetries_controller_test.rb
To prevent 400 from the server on registration.
> Forward also content-type to insights-client forwarding code

- webpack/ForemanInventoryUpload/Components/InventoryFilter/InventoryFilter.js
dropping the filter update after taxonomy changes,
as the page will reload anyway and it just feels like a bug when it updates for a second and then the page refreshes...
> update inventory filter only on initial load

- lib/foreman_inventory_upload/scripts/uploader.sh.erb
You have to delete `red_hat_inventory/uploads/uploader.sh` file to regenerate the uploader script.
> Forward exit code from curl to script

- app/models/inventory_sync/inventory_status.rb
It causes https://github.com/theforeman/foreman/blob/f5bfce8bc5cab43fa66c362d40ee843e0783fe72/app/models/host/managed.rb#L856 to fail.
> Fix missing to_status method.

- app/models/setting/rh_cloud.rb
- webpack/ForemanInventoryUpload/Components/InventorySettings/AdvancedSetting/AdvancedSettingsConstants.js
I have noticed that names/description of rh cloud options on settings page doesn't match with the one on configure > inventory upload page. 
This PR updates name and description of some rh cloud settings to make them consistent across foreman product.
> Fix RH Cloud settings name and description

- README.md
- lib/tasks/insights.rake
- lib/tasks/rh_cloud_inventory.rake
PR to fix https://bugzilla.redhat.com/show_bug.cgi?id=1957186
I have also interchanged the functionality of `rh_cloud_insights:sync` and `rh_cloud_inventory:sync` rake commands.
> Fix rh_cloud_insights and rh_cloud_inventory rake tasks

- app/controllers/insights_cloud/api/machine_telemetries_controller.rb
- app/models/insights_client_report_status.rb
- app/subscribers/foreman_rh_cloud/insights_subscriber.rb
- lib/foreman_rh_cloud/engine.rb
- test/models/insights_client_report_status_test.rb
```  
REPORTING             = 0 # host_registration_insights = true & getting data
NO_REPORT             = 1 # host_registration_insights = true & not getting data
NOT_MANAGED           = 2 # host_registration_insights = false
NOT_MANAGED_WITH_DATA = 3 # host_registration_insights = false & getting data
```
host_registration_insights | sending data? | Insights status
-- | -- | --
`nil` | yes | `Reporting (not set by registration)`
`nil` | no | `Not reporting (not set by registration)`
`TRUE` | yes | `Reporting`
`TRUE` | no | `Not reporting`
`FALSE` | yes | `Reporting (not set by registration)`
`FALSE` | no | `Not reporting (not set by registration)`
> New insights status for the host

- lib/foreman_inventory_upload/generators/slice.rb
- test/jobs/insights_full_sync_test.rb
- test/jobs/insights_resolutions_sync_test.rb
- test/jobs/insights_rules_sync_test.rb
- test/jobs/inventory_full_sync_test.rb
- test/unit/slice_generator_test.rb
* Fix tests that require tasks executor
* Convert all reported tag values to string
> [CP 2.3] Convert all reported tag values to string (#553)

- lib/foreman_inventory_upload/generators/fact_helpers.rb
- lib/foreman_inventory_upload/generators/slice.rb
- test/factories/inventory_upload_factories.rb
- test/unit/slice_generator_test.rb
* Omit malformed bios_uuid values
* Add exceptions to UUID fields
> [CP 2.3] Omit malformed bios_uuid values (#551)

- app/services/foreman_rh_cloud/cloud_auth.rb
- app/services/foreman_rh_cloud/cloud_request.rb
- app/services/foreman_rh_cloud/cloud_request_forwarder.rb
- app/services/foreman_rh_cloud/remediations_retriever.rb
- lib/insights_cloud/async/insights_full_sync.rb
- lib/insights_cloud/async/insights_resolutions_sync.rb
- lib/insights_cloud/async/insights_rules_sync.rb
- lib/inventory_sync/async/query_inventory_job.rb
* Refactor RestClient requests to a single factory
* Fix tests that require tasks executor
* Refactor all RestClient calls to a single method
Now all requests will inherit the same basic properties.
> [CP 2.3] Add proxy parameter to insights forwarded requests (#547)

- app/helpers/foreman_insights_deprecations_helper.rb
- app/overrides/old_plugin_deprecation.rb
Now on all pages you should see the same deprecation:
@MariSvirik Does it makes sense to you?
> Inject deprecation warning to old plugin

- lib/foreman_inventory_upload.rb
- lib/inventory_sync/async/host_result.rb
- lib/inventory_sync/async/inventory_hosts_sync.rb
- lib/inventory_sync/async/inventory_self_host_sync.rb
- lib/inventory_sync/async/query_inventory_job.rb
- test/jobs/inventory_hosts_sync_test.rb
- test/jobs/inventory_self_host_sync_test.rb
Since foreman host will not be registered to itself, it will not be synced using the regular hosts sync task. This is because hosts sync task assumes all hosts have subscription facet and on the cloud side they will be marked as managed by Satellite.
> Add self host sync task

- webpack/InsightsCloudSync/Components/RemediationModal/RemediationModal.scss
the remediation modal is not visible properly in reduced browser window.
> [CP 2.3] BZ 1967138 - remediation modal vertical nav overlap (#607)

- lib/inventory_sync/async/host_result.rb
- lib/inventory_sync/async/inventory_full_sync.rb
- lib/inventory_sync/async/inventory_hosts_sync.rb
- test/jobs/inventory_full_sync_test.rb
- test/jobs/inventory_hosts_sync_test.rb
* Use upsert to update inventory facets
* Fix InventoryFullSync statuses
* Fix empty response
> [CP 2.5] Handle duplicate InsightsFacets with upsert (#662)

- lib/inventory_sync/async/host_result.rb
- lib/inventory_sync/async/inventory_full_sync.rb
- lib/inventory_sync/async/inventory_hosts_sync.rb
- test/jobs/inventory_full_sync_test.rb
- test/jobs/inventory_hosts_sync_test.rb
* Use upsert to update inventory facets
* Fix InventoryFullSync statuses
* Fix empty response
> [CP 2.3] Handle duplicate InsightsFacets with upsert (#662)

- webpack/InsightsHostDetailsTab/InsightsTotalRiskChart.js
found that when there's a network error or host without recommendation, it may cause an infinite loop in the use-effect.
> fix infinite loop on total risk chart error

- webpack/InsightsCloudSync/Components/InsightsTable/table.scss
@redhat-cloud-services/frontend-components/index.css will be exported to Foreman via https://github.com/theforeman/foreman-js/pull/387
> Fix redhat-cloud-services/frontend-components scss import

- webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableActions.js
- webpack/InsightsCloudSync/Components/InsightsTable/InsightsTableHelpers.js
- webpack/InsightsCloudSync/Components/RemediationModal/RemediationActions.js
at the moment, when the user selects all recommendations from all pages
all host's resolutions was shown.
when the user views the insights table from the host page,
we should limit it to that specific host.
> limit remediation to specific host even if all selected on new host page

- app/controllers/insights_cloud/hits_controller.rb
- webpack/InsightsHostDetailsTab/InsightsTotalRiskChart.js
When accessing the overview tab on the new host page,
there are two network error responses with a 500 status.
the first one which tries the endpoint `/insights_cloud/hits/3` is because that specific host doesn't have recommendations.
and the second which comes right after that is failing due to the path ends with `/insights_cloud/hits/undefined`
this doesn't cause errors to be seen on the UI,
but rather an API call that could be avoided.
> BZ2069640 - prevent hits#show network errors

- package.json
this makes packaging easier by dropping the upper bound on the dependencies
> open @theforeman dependencies

- lib/insights_cloud/async/connector_playbook_execution_reporter_task.rb
- lib/insights_cloud/generators/playbook_progress_generator.rb
- test/unit/playbook_progress_generator_test.rb
consoleDot expects the `playbook_run_completed` status to indicate if the playbook succeeded for all hosts or indicate failure if at least one host failed.
@tahmidefaz @aleccohan -- could you verify this looks as you are expecting?
> job_finished_message should indicate overall playbook status

- lib/foreman_inventory_upload/async/delayed_start.rb
- lib/foreman_inventory_upload/async/generate_all_reports_job.rb
- lib/foreman_rh_cloud.rb
- lib/insights_cloud/async/insights_scheduled_sync.rb
- lib/inventory_sync/async/inventory_scheduled_sync.rb
Adding another option for randomizing task schedule. 
This correlates  to option 1 in https://github.com/theforeman/foreman_rh_cloud/pull/781
The idea is to wait in the main task before starting the execution of the sub-tasks.
> Schedule a random delay before execution

- app/models/concerns/rh_cloud_host.rb
This is adding missing search definitions which were forgotten when the statuses were introduced.
> Add host searching based on insights statuses

- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/SyncButton.js
- webpack/ForemanInventoryUpload/Components/PageHeader/components/SyncButton/__tests__/__snapshots__/SyncButton.test.js.snap
@ShimShtein let me know how this looks, I was able to get a devel box installed with the plugin and I don't see the icon anymore.
I switched the logic up based on this:
https://stackoverflow.com/a/70337425
> Remove icon from toolbar buttons on inventory page
